''' MRVC/image_IPP_2.py '''

# An IPP video compressor, similar to image_IPP.py, but now the blocks
# can also be I-type in a B-type frame. To decide the type, we compare
# the entropy of the blocks of the residue image resulting from the
# substraction of the current frame and the current prediction frame,
# with the entropy of the blocks of the current frame. If for a given
# block the residue has a higher entropy, then the block is
# intra-coded. Only the luma is considered. I-type blocks are
# generated by discarding the corresponding prediction blocks. The
# type of each block is transmitted to the decoder.

import DWT
import LP
import numpy as np
import L_DWT as L
import H_DWT as H
import deadzone as Q
import motion
import frame
import colors
import cv2
#import YCoCg as YUV
import RGB as YUV
import os
import random
import math

VIDEO_PREFIX = "../sequences/complete_stockholm/"
CODESTREAM_PREFIX = "/tmp/"
DECODED_VIDEO_PREFIX = "/tmp/decoder_"
#Q_STEP = 128
N_FRAMES = 16
LOG2_BLOCK_SIDE = 4 # BLOCK_SIZE = 1 << LOG2_BLOCK_SIDE
BLOCK_SIDE = 2**LOG2_BLOCK_SIDE 
N_LEVELS = 5
block_x_side = BLOCK_SIDE
block_y_side = BLOCK_SIDE

def entropy(sequence_of_symbols):
    '''In bits/symbol.'''
    value, counts = np.unique(sequence_of_symbols, return_counts = True)
    probs = counts / len(sequence_of_symbols)
    n_classes = np.count_nonzero(probs)

    if n_classes <= 1:
        return 0

    entropy = 0.
    for i in probs:
        entropy -= i * math.log(i, 2)

    return entropy

def norm(x):
    return (frame.normalize(x)*255).astype(np.uint8)

def clip(x):
    return(np.clip(x, 0 ,255).astype(np.uint8))

def E_codec(E_k, n_levels, q_step, prefix, k):
    decom = DWT.analyze(E_k, n_levels)
    #print(decom[0])
    LL = decom[0]
    decom[0] = Q.quantize(LL, q_step)
    for resolution in decom[1:]:
        resolution = list(resolution)
        LH = resolution[0]
        resolution[0][:] = Q.quantize(LH, q_step)
        HL = resolution[1]
        resolution[1][:] = Q.quantize(HL, q_step)
        HH = resolution[2]
        resolution[2][:] = Q.quantize(HH, q_step)
        resolution = tuple(resolution)
    DWT.write(decom, prefix, k, n_levels)
    LL = decom[0]
    #print(LL)
    decom[0] = Q.dequantize(LL, q_step)
    #print(decom[0])
    for resolution in decom[1:]:
        resolution = list(resolution)
        LH = resolution[0]
        resolution[0][:] = Q.dequantize(LH, q_step)
        HL = resolution[1]
        resolution[1][:] = Q.dequantize(HL, q_step)
        HH = resolution[2]
        resolution[2][:] = Q.dequantize(HH, q_step)
        resolution = tuple(resolution)
    #print("->", decom[1][0])
    dq_E_k = DWT.synthesize(decom, n_levels)
    return dq_E_k
    #return E_k-dq_E_k
    #return E_k

# https://stackoverflow.com/questions/34123272/ffmpeg-transmux-mpegts-to-mp4-gives-error-muxer-does-not-support-non-seekable: ffmpeg -blocksize 1 -i /tmp/original_000.png -blocksize 1 -flush_packets 1 -movflags frag_keyframe+empty_moov -f mp4 - | ffmpeg -blocksize 1 -i - -blocksize 1 -flush_packets 1 /tmp/decoded_%3d.png

# https://video.stackexchange.com/questions/16958/ffmpeg-encode-in-all-i-mode-h264-and-h265-streams: fmpeg -i input -c:v libx264 -intra output / ffmpeg -i input -c:v libx265 -x265-params frame-threads=4:keyint=1:ref=1:no-open-gop=1:weightp=0:weightb=0:cutree=0:rc-lookahead=0:bframes=0:scenecut=0:b-adapt=0:repeat-headers=1 output
def E_codec2(E_k, prefix, k):
    print("Error", E_k.max(), E_k.min())
    L.write(YUV.to_RGB(E_k), prefix + "_to_mp4", k)
    #frame.write(YUV.to_RGB(E_k), prefix + "_to_mp4", k)
    os.system(f"ffmpeg -loglevel fatal -y -i {prefix}_to_mp4_{k:03d}_LL.png -crf 1 {prefix}_{k:03d}.mp4")
    os.system(f"ffmpeg -loglevel fatal -y -i {prefix}_{k:03d}.mp4 {prefix}_from_mp4_{k:03d}_LL.png")
    dq_E_k = YUV.from_RGB(L.read(prefix + "_from_mp4", k))
    #dq_E_k = (YUV.from_RGB(frame.read(prefix + "_from_mp4", k)))
    return dq_E_k.astype(np.float64)

def I_codec(E_k, prefix, k, q_step):
    print("Error", E_k.max(), E_k.min())
    #frame.write(YUV.to_RGB(E_k), prefix + "before_", k)
    frame.write(YUV.to_RGB(E_k) + 128, prefix + "before_", k)
    os.system(f"ffmpeg -loglevel fatal -y -i {prefix}before_{k:03d}.png -crf {q_step} {prefix}{k:03d}.mp4")
    os.system(f"ffmpeg -loglevel fatal -y -i {prefix}{k:03d}.mp4 {prefix}{k:03d}.png")
    #dq_E_k = (YUV.from_RGB(frame.read(prefix, k)))
    dq_E_k = (YUV.from_RGB(frame.read(prefix, k) - 128))
    return dq_E_k

def E_codec4(E_k, prefix, k, q_step):
    print("Error", E_k.max(), E_k.min())
    #frame.write(YUV.to_RGB(E_k), prefix + "before_", k)
    #frame.write(YUV.to_RGB(E_k) + 128, prefix + "before_", k)
    frame.write(clip(YUV.to_RGB(E_k) + 128), prefix + "before_", k)
    #frame.write(clip(YUV.to_RGB(E_k)), prefix + "before_", k)
    os.system(f"ffmpeg -loglevel fatal -y -i {prefix}before_{k:03d}.png -crf {q_step} {prefix}{k:03d}.mp4")
    os.system(f"ffmpeg -loglevel fatal -y -i {prefix}{k:03d}.mp4 {prefix}{k:03d}.png")
    #dq_E_k = YUV.from_RGB(frame.read(prefix, k))
    dq_E_k = YUV.from_RGB(frame.read(prefix, k) - 128)
    #dq_E_k = YUV.from_RGB(frame.read(prefix, k))
    return dq_E_k

def V_codec(motion, n_levels, prefix, frame_number):
    #print(prefix+"_y")
    pyramid = LP.analyze(motion, n_levels)
    #pyramid[0][:,:,:] = 0
    frame.write(pyramid[0][...,0], prefix+"_y_", frame_number)
    frame.write(pyramid[0][...,1], prefix+"_x_", frame_number)
    for resolution in pyramid[1:]:
        resolution[...] = 0
    reconstructed_motion = LP.synthesize(pyramid, n_levels)
    #print(motion-reconstructed_motion[:motion.shape[0], :motion.shape[1], :])
    return np.rint(reconstructed_motion).astype(np.int16)
    #return reconstructed_motion.astype(np.int16)
    #decom_Y = pywt.wavedec2(motion[:,:,0], 'db1', mode='per', levels=3)
    #decom_X = pywt.wavedec2(motion[:,:,1], 'db1', mode='per', levels=3)
    #L.write(decom_Y[0], prefix, k)
    #L.write(decom_Y[1], prefix, k)
    #H_subbands_decom_Y = decom_Y[1:]
    #for resolution in H_subbands_decom_Y:
    #    resolution[0][:,:] = 0
    #    resolution[1][:,:] = 0
    #    resolution[2][:,:] = 0
    #H_subbands_decom_X = decom_X[1:]
    #for resolution in H_subbands_decom_X:
    #    resolution[0][:,:] = 0
    #    resolution[1][:,:] = 0
    #    resolution[2][:,:] = 0
    #pywt.waverec2(decom_Y, 'db1')
    #pywt.waverec2(decom_X, 'db1')
    #_motion = np.empty_like(motion)
    #_motion[:,:,0] = decom_Y[:,:]
    #_motion[:,:,0] = decom_X[:,:]
    #return _motion

def _V_codec(motion, n_levels, prefix, frame_number):
    pyramid = np.rint(motion).astype(np.int16)
    frame.write(pyramid[:,:,0], prefix+"_y_", frame_number)
    frame.write(pyramid[:,:,1], prefix+"_x_", frame_number)
    return pyramid

def encode(video, n_frames, q_step):
    try:
        k = 0
        #W_k = frame.read(video, k)
        W_k = frame.read(video, k) - 128
        flow = np.zeros((W_k.shape[0], W_k.shape[1], 2), dtype=np.float32)
        V_k = YUV.from_RGB(W_k) # (a)
        block_types = np.zeros((int(V_k.shape[0]/block_y_side), int(V_k.shape[1]/block_x_side)), dtype=np.uint8)
        V_k_1 = V_k.copy() # (b)
        E_k = V_k.copy() # (f)
        dequantized_E_k = I_codec(E_k, f"{video}codestream_", 0, q_step) # (g and h)
        reconstructed_V_k = dequantized_E_k # (i)
        #frame.debug_write(clip(YUV.to_RGB(reconstructed_V_k)), f"{video}reconstructed_", k) # Decoder's output
        frame.debug_write(clip(YUV.to_RGB(reconstructed_V_k) + 128), f"{video}reconstructed_", k) # Decoder's output
        reconstructed_V_k_1 = reconstructed_V_k # (j)
        for k in range(1, n_frames):
            #W_k = frame.read(video, k)
            W_k = frame.read(video, k) - 128
            V_k = YUV.from_RGB(W_k) # (a)
            initial_flow = np.zeros((V_k.shape[0], V_k.shape[1], 2), dtype=np.float32)
            flow = motion.estimate(V_k[...,0], V_k_1[...,0], initial_flow) # (c)
            print("COMPUTED flow", flow.max(), flow.min())
            V_k_1 = V_k.copy() # (b)
            reconstructed_flow = V_codec(flow, LOG2_BLOCK_SIDE, f"{video}motion", k) # (d and e)
            print("USED flow", reconstructed_flow.max(), reconstructed_flow.min())
            #frame.debug_write(motion.colorize(flow), f"{codestream}flow", k)
            #frame.debug_write(motion.colorize(reconstructed_flow.astype(np.float32)), f"{codestream}reconstructed_flow", k)
            #print("reconstructed_V_k_1", reconstructed_V_k_1.max(), reconstructed_V_k_1.min())
            prediction_V_k = motion.make_prediction(reconstructed_V_k_1, reconstructed_flow) # (j)
            #frame.debug_write(clip(YUV.to_RGB(prediction_V_k)), f"{codestream}encoder_prediction", k)
            E_k = V_k - prediction_V_k[:V_k.shape[0], :V_k.shape[1], :] # (f)
            #E_k = V_k - prediction_V_k[:V_k.shape[0], :V_k.shape[1], :] - 128 # (f)
            print("E_k", E_k.max(), E_k.min())
            '''
            for y in range(int(V_k.shape[0]/block_y_side)):
                for x in range(int(V_k.shape[1]/block_x_side)):
                    E_k_block_entropy = \
                        entropy(E_k[y*block_y_side:(y+1)*block_y_side,
                                    x*block_x_side:(x+1)*block_x_side][..., 0])
                    V_k_block_entropy = \
                        entropy(V_k[y*block_y_side:(y+1)*block_y_side,
                                    x*block_x_side:(x+1)*block_x_side][..., 0])
                    if E_k_block_entropy < V_k_block_entropy:
                        print('B', end='')
                        block_types[y, x] = 0
                    else:
                        print('I', end='')
                        E_k[y*block_y_side:(y+1)*block_y_side,
                            x*block_x_side:(x+1)*block_x_side] = \
                                V_k[y*block_y_side:(y+1)*block_y_side,
                                    x*block_x_side:(x+1)*block_x_side]
                        #prediction_V_k[y*block_y_side:(y+1)*block_y_side,
                        #    x*block_x_side:(x+1)*block_x_side] = 128
                        prediction_V_k[y*block_y_side:(y+1)*block_y_side,
                            x*block_x_side:(x+1)*block_x_side] = 0
                        block_types[y, x] = 1
                print('')
            '''
            #E_k = np.clip(E_k, 0, 255)
            
            #frame.debug_write(clip(YUV.to_RGB(E_k)+128), f"{codestream}encoder_prediction_error", k)
            dequantized_E_k = E_codec4(E_k, f"{video}codestream_", k, q_step) # (g and h)
            print("dequantized_E_k", dequantized_E_k.max(), dequantized_E_k.min())
            #frame.debug_write(clip(YUV.to_RGB(dequantized_E_k)), f"{codestream}encoder_dequantized_prediction_error", k)
            reconstructed_V_k = dequantized_E_k + prediction_V_k[:dequantized_E_k.shape[0], :dequantized_E_k.shape[1]] # (i)
            print("reconstructed_V_k", reconstructed_V_k.max(), reconstructed_V_k.min())
            #reconstructed_V_k -= 128
            #reconstructed_V_k = np.clip(reconstructed_V_k, 0, 255)
            frame.debug_write(clip(YUV.to_RGB(reconstructed_V_k) + 128), f"{video}reconstructed_", k) # Decoder's output
            reconstructed_V_k_1 = reconstructed_V_k # (j)
    except:
        print(colors.red(f'image_IPP_step.encode(video="{video}", codestream="{codestream}", n_frames={n_frames}, q_step={q_step})'))
        raise

def compute_br(prefix, frames_per_second, frame_shape, n_frames):
    print("*"*80, prefix)
    #os.system(f"ffmpeg -y -i {prefix}_from_mp4_%03d.png -c:v libx264 -x264-params keyint=1 -crf 0 /tmp/image_IPP_texture.mp4")
    #os.system(f"ffmpeg -f concat -safe 0 -i <(for f in {prefix}_*.mp4; do echo \"file '$PWD/$f'\"; done) -c copy /tmp/image_IPP_texture.mp4")
    os.system(f"ffmpeg -loglevel fatal -y -f concat -safe 0 -i <(for f in {prefix}_*.mp4; do echo \"file '$f'\"; done) -c copy /tmp/image_IPP_texture.mp4")
    print(f"ffmpeg -loglevel fatal -y -i {prefix}motion_y_%03d.png -c:v libx264 -x264-params keyint=1 -crf 0 /tmp/image_IPP_motion_y.mp4")
    os.system(f"ffmpeg -loglevel fatal -y -i {prefix}motion_y_%03d.png -c:v libx264 -x264-params keyint=1 -crf 0 /tmp/image_IPP_motion_y.mp4")
    os.system(f"ffmpeg -loglevel fatal -y -i {prefix}motion_x_%03d.png -c:v libx264 -x264-params keyint=1 -crf 0 /tmp/image_IPP_motion_x.mp4")

    frame_height = frame_shape[0]
    frame_width = frame_shape[1]
    n_channels = frame_shape[2]
    sequence_time = n_frames/frames_per_second
    print(f"height={frame_height} width={frame_width} n_channels={n_channels} sequence_time={sequence_time}")

    texture_bytes = os.path.getsize("/tmp/image_IPP_texture.mp4")
    kbps = texture_bytes*8/sequence_time/1000
    bpp = texture_bytes*8/(frame_width*frame_height*n_channels*n_frames)
    print(f"texture: {texture_bytes} bytes, {kbps} kbps, {bpp} bpp")

    total_bytes = texture_bytes
    motion_y_bytes = os.path.getsize("/tmp/image_IPP_motion_y.mp4")
    kbps = motion_y_bytes*8/sequence_time/1000
    print(f"motion (Y direction): {motion_y_bytes} bytes, {kbps} kbps")

    total_bytes += motion_y_bytes
    motion_x_bytes = os.path.getsize("/tmp/image_IPP_motion_x.mp4")
    kbps = motion_x_bytes*8/sequence_time/1000
    print(f"motion (X direction): {motion_x_bytes} bytes, {kbps} kbps")

    total_bytes += motion_x_bytes
    kbps = total_bytes*8/sequence_time/1000
    bpp = total_bytes*8/(frame_width*frame_height*n_channels*n_frames)
    print(f"total: {kbps} kbps, {bpp} bpp")

    return kbps, bpp
